import Head from 'next/head';
import styles from '@/styles/Home.module.scss';
import clsx from 'clsx';
import axios from 'axios';
import Image from 'next/image';

export default function Home({ meals }) {
	const newMeals = meals.slice(0, 6);
	console.log(newMeals);

	return (
		<>
			<Head>
				<title>Next Recipe</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={clsx(styles.main)}>
				<figure className='visual'>
					<article className='bg'>
						{newMeals.map((item) => (
							<div key={item.idMeal} className='pic' style={{ position: 'relative', width: 400, height: 300 }}>
								<Image
									src={item.strMealThumb}
									alt={item.strMeal}
									priority
									fill
									quality={100}
									style={{ objectFit: 'cover' }}
									//이미지 속성이 fill로 지정되어 있을경우 frame크기에 상관없이 초기 로딩시 전체 브라우저 크기의 100vw크기의 용량으로 가져오기 때문에 브라우저 폭에 출력될 크기를 지정해서 이미지 성능 향상

									sizes='(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw'
								/>
							</div>
						))}
					</article>

					<article className='list'>
						{newMeals.map((item) => (
							<h2 key={item.idMeal}>{item.strMeal}</h2>
						))}
					</article>
				</figure>
			</main>
		</>
	);
}

// ssg방식 (한번만 build됨)
export async function getStaticProps() {
	//props로 데이터 넘길때에는 data안쪽의 값까지 뽑아낸다음에 전달
	const { data } = await axios.get('/filter.php?c=Seafood');
	console.log('response', data);

	return {
		//이전에 가져온 응답 데이터를 props 속성에 할당하여 해당 데이터를 페이지 컴포넌트 내에서 사용
		props: data,
		//아래 추가하면 ISR 방식으로 변경
		//24시간마다 재생성
		revalidate: 60 * 60 * 24,
	};
}
